# Generated by Django 5.2.8 on 2026-02-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('complaint', 'Complaint Report'), ('eedback', 'Feedback')])),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
